server:
  port: 2200
spring:
  application:
    name: microservicecloud-consumer
eureka:
  client:
    service-url: 
      defaultZone: http://localhost:7001/eureka,http://eureka7002.com:7002/eureka/,http://eureka7003.com:7003/eureka/  
  instance:
    instance-id: microservicecloud-consumer2200
    prefer-ip-address: true   #访问路径可以显示IP地址     
  
  
  
  
  
  